// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avsdrcsjqoqcdmketnze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2c2RyY3NqcW9xY2Rta2V0bnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODY3NTMsImV4cCI6MjA2MjI2Mjc1M30.c9fKR2-iWVYPbiEmDldFthMbIvQkfa1dZx9n21gH_08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);